# The following variables are mandatory
SOFTWARE_PATH = ../..
BINARY = Calculator
# A Strings.txt file must be present in the program sources directory when defining the EEPROM_IMAGE variable (and Strings.h must be included where required in the sources)
EEPROM_IMAGE =
SOURCES = Interface.c Main.c Math.c

# Mandatory include to have all automated rules
include ../../../Tools/Rules.mk