# The following variables are mandatory
SOFTWARE_PATH = ../..
BINARY = Tests
# A Strings.txt file must be present in the program sources directory when defining the EEPROM_IMAGE variable (and Strings.h must be included where required in the sources)
EEPROM_IMAGE =
SOURCES = Main.c Test_Clock_Speed.c Test_External_EEPROM.c Test_Internal_EEPROM.c Test_Random.c Test_Screen_Speed.c

# Mandatory include to have all automated rules
include ../../../Tools/Rules.mk