# Makefile for Text Games System PC programmer.
CC = gcc
CCFLAGS = -W -Wall
BINARY_NAME = Programmer

all:
	$(CC) $(CCFLAGS) Hex_Parser.c Main.c UART.c -o $(BINARY_NAME)

clean:
	rm -f $(BINARY_NAME) $(BINARY_NAME).exe