# The following variables are mandatory
SOFTWARE_PATH = ../..
BINARY = Games
# A Strings.txt file must be present in the program sources directory when defining the EEPROM_IMAGE variable (and Strings.h must be included where required in the sources)
EEPROM_IMAGE = Games_EEPROM_Image.bin
SOURCES = Brain_Calculation.c Demo.c Loto.c Main.c Numbers.c Shared_Buffer.c Wumpus.c

# Mandatory include to have all automated rules
include ../../../Tools/Rules.mk