# The following variables are mandatory
SOFTWARE_PATH = ../../..
BINARY = Timestamp_Storage
# A Strings.txt file must be present in the program sources directory when defining the EEPROM_IMAGE variable (and Strings.h must be included where required in the sources)
EEPROM_IMAGE =
SOURCES = Main.c

# Mandatory include to have all automated rules
include ../../../../Tools/Rules.mk