# The following variables are mandatory
SOFTWARE_PATH = ../..
BINARY = Cassaforte
# A Strings.txt file must be present in the program sources directory when defining the EEPROM_IMAGE variable (and Strings.h must be included where required in the sources)
EEPROM_IMAGE =
SOURCES = Interface.c Main.c Menu_Delete_All_Records.c Menu_Delete_Record.c Menu_Display_Record_Content.c Menu_List_Records.c Menu_Main.c Menu_New_Record.c Menu_Rename_Record.c Records.c

# Mandatory include to have all automated rules
include ../../../Tools/Rules.mk