/** @file Parser.c
 * @see Parser.h for description.
 * @author Adrien RICCIARDI
 */
#include <stdio.h>
#include <string.h>
#include "Parser.h"

//-------------------------------------------------------------------------------------------------
// Private variables
//-------------------------------------------------------------------------------------------------
static FILE *File_Resources, *File_Header, *File_EEPROM;

//-------------------------------------------------------------------------------------------------
// Private functions
//-------------------------------------------------------------------------------------------------
/** Extract string value from raw string read from file.
 * @param String_Input The raw string.
 * @param String_Output The string value if there is one.
 * @return 0 if a string value was successfully extracted (String_Output is valid, it is not valid in all other cases),
 * @return -1 if there is no string value,
 * @return -2 if the string value doesn't start with a quote,
 * @return -3 if the string value doesn't end with a quote,
 * @return -4 if there is a quote into the string (use escape sequence \" to specify a quote),
 * @return -5 if there is an unrecognized escape sequence.
 */
int ExtractStringValue(char *String_Input, char *String_Output)
{
	// Delete preceding spaces
	while ((*String_Input != 0) && ((*String_Input == 32) || (*String_Input == '\t'))) String_Input++;
	// If we reached 0 we can deduce that there is no string
	if (*String_Input == 0) return -1;
	// If the first character is not a quote, there is a problem
	if (*String_Input != '"') return -2;
	// Bypass first quote
	String_Input++;
	
	// Copy string value into output string
	while (1)
	{
		// Handle escape sequences
		if (*String_Input == '\\')
		{
			String_Input++;
			switch (*String_Input)
			{
				case 'n':
					*String_Output = '\n';
					break;
				case 'r':
					*String_Output = '\r';
					break;
				case '"':
					*String_Output = '"';
					break;
				case '\\':
					*String_Output = '\\';
					break;
				default:
					return -5;
			}
			// Adjust pointers, as we can reach this code only if the escape sequence was recognized
			String_Input++;
			String_Output++;
		}
		// Does the string end with a quote ?
		else if (*String_Input == '"')
		{
			// Bypass quote
			String_Input++;
			break;
		}
		// There is a problem if the string ends now
		else if (*String_Input == 0) return -3;
		// Copy character
		else
		{
			*String_Output = *String_Input;
			String_Input++;
			String_Output++;
		}					
	}
	
	// Check is there are only spaces or tabulations after the closing quote
	while ((*String_Input != 0) && ((*String_Input == 32) || (*String_Input == '\t'))) String_Input++;
	// If we reached 0 then the string value has been successfully extracted
	if (*String_Input == 0)
	{
		*String_Output = 0; // End output string
		return 0;
	}
	// Otherwise there is a "normal" quote in the middle of the string
	return -4;
}

//-------------------------------------------------------------------------------------------------
// Public functions
//-------------------------------------------------------------------------------------------------
void ParserInit(FILE *Input_File_Resources, FILE *Output_File_Header, FILE *Output_File_EEPROM)
{
	File_Resources = Input_File_Resources;
	File_Header = Output_File_Header;
	File_EEPROM = Output_File_EEPROM;
	
	// Generate header structure
	fprintf(File_Header, "/** File automatically generated by EEPROM_Strings_Converter. */\n");
	fprintf(File_Header, "#ifndef H_STRINGS_H\n#define H_STRINGS_H\n\n");
}

int ParserProcessFiles(void)
{
	int Line_Number = 1, Length, Current_String_Address = 0;
	char String_Identifier[16385], String_Value[16385], String_Temp[16385];
	
	while (1)
	{
		// Read identifier
		fscanf(File_Resources, "%s", String_Identifier);
		if (feof(File_Resources)) break;
	
		// Read string value
		fgets(String_Temp, sizeof(String_Value), File_Resources);
		// Remove carriage return if it exists
		Length = strlen(String_Temp);
		if ((Length > 0) && (String_Temp[Length - 1] == '\n')) String_Temp[Length - 1] = 0;
		
		// Extract value
		switch (ExtractStringValue(String_Temp, String_Value))
		{
			case -1:
				printf("Parsing error at line %d : no string value provided.\n", Line_Number);
				return 0;
			case -2:
				printf("Parsing error at line %d : the string value doesn't start with a quote.\n", Line_Number);
				return 0;
			case -3:
				printf("Parsing error at line %d : the string value doesn't end with a quote.\n", Line_Number);
				return 0;
			case -4:
				printf("Parsing error at line %d : there is a quote in the middle of the string (use \\\" instead).\n", Line_Number);
				return 0;
			case -5:
				printf("Parsing error at line %d : unrecognized escape sequence.\n", Line_Number);
				return 0;
		}
		Line_Number++;
		
		// Write string address to header file
		fprintf(File_Header, "#define %s %d\n", String_Identifier, Current_String_Address);
		Length = strlen(String_Value) + 1; // + 1 to take account of the final 0
		Current_String_Address += Length;
		
		// Write string value to EEPROM file
		fwrite(String_Value, Length, 1, File_EEPROM);
	}
	
	// End header file
	fprintf(File_Header, "\n#endif");
	
	// Parsing succeeded
	return 1;
}
