# Gather all shared variables

# Paths
TEXT_GAMES_SYSTEM_BINARIES_PATH = $(SOFTWARE_PATH)/Binaries
TEXT_GAMES_SYSTEM_INCLUDES_PATH = $(SOFTWARE_PATH)/Includes
TEXT_GAMES_SYSTEM_OBJECTS_PATH = $(SOFTWARE_PATH)/Objects
TEXT_GAMES_SYSTEM_TOOLS_PATH = $(SOFTWARE_PATH)/../Tools

# Parameters
TEXT_GAMES_SYSTEM_INCLUDES = -I $(TEXT_GAMES_SYSTEM_INCLUDES_PATH) -I $(TEXT_GAMES_SYSTEM_INCLUDES_PATH)/System
TEXT_GAMES_SYSTEM_CCFLAGS = -obj $(PROGRAM_OBJECTS_PATH) $(TEXT_GAMES_SYSTEM_INCLUDES) -t PIC16F876
TEXT_GAMES_SYSTEM_LDFLAGS = -ld $(SOFTWARE_PATH) $(SOFTWARE_PATH)/Binaries/System.lib $(SOURCEBOOST_PATH)/Lib/libc.pic16.lib -t PIC16F876
TEXT_GAMES_SYSTEM_PROGRAMMER_UART_DEVICE_NAME = "COM1"
TEXT_GAMES_SYSTEM_EEPROM_SIZE = 4096

# Programs
TEXT_GAMES_SYSTEM_CC = $(SOURCEBOOST_PATH)/boostc_pic16.exe
TEXT_GAMES_SYSTEM_LD = $(SOURCEBOOST_PATH)/boostlink_picmicro.exe
TEXT_GAMES_SYSTEM_EEPROM_STRINGS_CONVERTER = $(TEXT_GAMES_SYSTEM_TOOLS_PATH)/EEPROM_Strings_Converter/EEPROM_Strings_Converter
